### ISSUE TITLE
service.checkin() problem

### ISSUE THREAD

**Issue by hzzjucn** [Akdeniz/google-play-crawler#22]
Hi,
Thank you for your api, it worked great.
But recently, I have found an error when checkin, please check the message shown below. What is the reason? Thank you very much.

Exception in thread "main" com.akdeniz.googleplaycrawler.GooglePlayException: <HTML>
<HEAD>
<TITLE>Not Found</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Not Found</H1>

<H2>Error 404</H2>

</BODY>
</HTML>

```
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:489)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:449)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:429)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.loginAC2DM(GooglePlayAPI.java:163)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.checkin(GooglePlayAPI.java:148)
at com.akdeniz.googleplaycrawler.test.TestGooglePlay.main(TestGooglePlay.java:38)
```

**Comment by CoCumis** [comment]
Unfortunately I have the same problem. Doesn't google change checkin url?

**Comment by Fuzion24** [comment]
It's unlikely/impossible that the checkin endpoint would change as this would require upgrading system level framework for all google play devices.  On most devices, this is only possible via a carrier/manufacturer OTA update...

**Comment by qwertydzen** [comment]
I have the same problem with not found

**Comment by Akdeniz** [comment]
[Last commit](https://github.com/Akdeniz/google-play-crawler/commit/ef8d6b66be764b03610a9336e54e69df95cfeaba) should solve this problem.

**Comment by hzzjucn** [comment]
Thanks for your help! It's OK now.

**Comment by achyut007** [comment]
Hi,
I am getting issue while trying to sign in into google account. I have automated script to download the apk files from Google Play store. The script was running fine till last week. But, recently getting following error related to akdeniz.googleplaycrawler library:

Exception in thread "main" com.akdeniz.googleplaycrawler.GooglePlayException: Error=BadAuthentication
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:522)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:482)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executePost(GooglePlayAPI.java:462)

and so on...
Currently, I am using googleplaycrawler-0.3.jar to download apk files from play store.
How can I resolve it? Can you please help me in this issue?

Thank you,
Achyut
