### ISSUE TITLE
How to download paid apps

### ISSUE THREAD

**Issue by atiqsayyed** [Akdeniz/google-play-crawler#46]
Hi, 

I tried to figure out how to download paid apps, but i was not able to find the way to do it.

It would be helpful if you can tell me how this flow works

Thanks

**Comment by atiqsayyed** [comment]
Can anyone please help me out with this, i have google wallet lined to my account, i'm trying to download the app but it throws this error

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0
    at java.util.Collections$EmptyList.get(Collections.java:3212)
    at com.akdeniz.googleplaycrawler.GooglePlay$AndroidAppDeliveryData.getDownloadAuthCookie(GooglePlay.java:525)
    at com.akdeniz.googleplaycrawler.GooglePlayAPI.download(GooglePlayAPI.java:318)

Any help would be appreciated.

**Comment by Akdeniz** [comment]
Hi @atiqsayyed,

You can not buy applications with this project, it is not implemented. 

Though there is a pull request https://github.com/Akdeniz/google-play-crawler/pull/24 which I haven't tested myself about downloading already purchased applications but i think that is not you are asking for..

But you can implement it yourself by dumping actual application traffic with proxy and finding out what is going on.
