### ISSUE TITLE
Error in shouldDownload - TestGooglePlay.java

### ISSUE THREAD

**Issue by abent** [Akdeniz/google-play-crawler#49]
I got this error:
Exception in thread "main" com.akdeniz.googleplaycrawler.GooglePlayException: <HTML>
<HEAD>
<TITLE>Forbidden</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">

<H1>Forbidden</H1>

<H2>Error 403</H2>

</BODY>
</HTML>

```
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeHttpRequest(GooglePlayAPI.java:522)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeGet(GooglePlayAPI.java:513)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.executeDownload(GooglePlayAPI.java:356)
at com.akdeniz.googleplaycrawler.GooglePlayAPI.download(GooglePlayAPI.java:320)
at com.akdeniz.googleplaycrawler.TestGooglePlayCrawler.shouldDownload(TestGooglePlayCrawler.java:149)
at com.akdeniz.googleplaycrawler.TestGooglePlayCrawler.main(TestGooglePlayCrawler.java:163)
```

Can you help me with this ? Thank you!

**Comment by atiqsayyed** [comment]
Kindly check config file and add your google username and password to it.

**Comment by abent** [comment]
@atiqsayyed : But sometimes it was ok, sometimes it got that error? I don't know why?.

**Comment by atiqsayyed** [comment]
Even I had the same problem, if you try to hit google server multiple times it may block you. so try to use multiple username and password.
